"""all without indexes

Revision ID: 33292213c4b2
Revises: c8c0d5fc3fe1
Create Date: 2025-03-09 13:46:59.048183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33292213c4b2'
down_revision: Union[str, None] = 'c8c0d5fc3fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_surname', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('last_school', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_surname', 'users', ['surname'], unique=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    # ### end Alembic commands ###
