"""all without indexes3

Revision ID: b716eefbfdf0
Revises: b6998f9f07f2
Create Date: 2025-03-09 13:53:39.038025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b716eefbfdf0'
down_revision: Union[str, None] = 'b6998f9f07f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AdditionalInformation', sa.Column('Information', sa.Integer(), nullable=False))
    op.drop_column('AdditionalInformation', 'n')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AdditionalInformation', sa.Column('n', sa.INTEGER(), nullable=False))
    op.drop_column('AdditionalInformation', 'Information')
    # ### end Alembic commands ###
